"""Synthetic symmetry probes for sparse feature recovery.

The utilities in this module are deliberately small: they let us test whether a
known group action can be used as unlabeled augmentation for sparse dictionary
recovery, a toy analogue of sparse-autoencoder feature recovery in activations.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from sklearn.decomposition import NMF

FloatArray = NDArray[np.float64]


@dataclass(frozen=True)
class OrbitSparseConfig:
    """Configuration for a cyclic-orbit sparse coding problem."""

    ambient_dim: int = 24
    orbit_size: int = 4
    n_orbits: int = 6
    sparsity: int = 3
    noise: float = 0.08
    dictionary_seed: int = 0

    @property
    def n_features(self) -> int:
        """Number of latent features in the ground-truth dictionary."""

        return self.orbit_size * self.n_orbits

    @property
    def shift(self) -> int:
        """Coordinate shift that realizes one generator step of the cyclic group."""

        if self.ambient_dim % self.orbit_size != 0:
            msg = "ambient_dim must be divisible by orbit_size"
            raise ValueError(msg)
        return self.ambient_dim // self.orbit_size


def normalize_rows(matrix: FloatArray, eps: float = 1e-12) -> FloatArray:
    """Return a copy of ``matrix`` with unit-L2 rows."""

    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return matrix / np.maximum(norms, eps)


def make_orbit_dictionary(config: OrbitSparseConfig) -> FloatArray:
    """Build nonnegative features arranged in cyclic-shift orbits.

    Each base feature is sparse and nonnegative. Its orbit is generated by
    repeatedly rolling coordinates by ``config.shift``. The resulting rows are
    the ground-truth dictionary atoms.
    """

    rng = np.random.default_rng(config.dictionary_seed)
    atoms: list[FloatArray] = []
    for _ in range(config.n_orbits):
        base = rng.gamma(shape=1.0, scale=1.0, size=config.ambient_dim)
        base *= rng.random(config.ambient_dim) < 0.35
        base += 1e-3 * rng.random(config.ambient_dim)
        base /= np.linalg.norm(base)
        for step in range(config.orbit_size):
            atoms.append(np.roll(base, step * config.shift))
    return np.asarray(atoms, dtype=np.float64)


def sample_sparse_codes(
    n_samples: int, config: OrbitSparseConfig, *, seed: int
) -> FloatArray:
    """Sample nonnegative sparse latent codes."""

    rng = np.random.default_rng(seed)
    codes = np.zeros((n_samples, config.n_features), dtype=np.float64)
    for row in codes:
        active = rng.choice(config.n_features, config.sparsity, replace=False)
        row[active] = rng.gamma(shape=2.0, scale=1.0, size=config.sparsity)
    return codes


def sample_observations(
    dictionary: FloatArray, n_samples: int, config: OrbitSparseConfig, *, seed: int
) -> tuple[FloatArray, FloatArray]:
    """Generate nonnegative observations from sparse latent codes."""

    codes = sample_sparse_codes(n_samples, config, seed=seed)
    rng = np.random.default_rng(seed + 1_000_003)
    noise = config.noise * rng.gamma(shape=1.0, scale=1.0, size=(n_samples, config.ambient_dim))
    return codes @ dictionary + noise, codes


def cyclic_augment(observations: FloatArray, config: OrbitSparseConfig) -> FloatArray:
    """Stack every cyclic transform of the observations.

    This is label-free: it assumes only that the representation has a known
    cyclic action, not that the active latent features are observed.
    """

    return np.vstack(
        [np.roll(observations, step * config.shift, axis=1) for step in range(config.orbit_size)]
    )


def fit_nmf_dictionary(
    observations: FloatArray,
    n_components: int,
    *,
    seed: int,
    max_iter: int = 500,
    alpha: float = 0.05,
) -> tuple[FloatArray, float, int]:
    """Fit a sparse nonnegative dictionary and return atoms, MSE, and iterations."""

    model = NMF(
        n_components=n_components,
        init="random",
        random_state=seed,
        max_iter=max_iter,
        solver="cd",
        l1_ratio=0.7,
        alpha_W=alpha,
        alpha_H=alpha,
    )
    weights = model.fit_transform(observations)
    atoms = np.asarray(model.components_, dtype=np.float64)
    mse = float(np.mean((observations - weights @ atoms) ** 2))
    return atoms, mse, int(model.n_iter_)


def feature_recovery(learned_atoms: FloatArray, true_atoms: FloatArray) -> tuple[float, float]:
    """Measure ground-truth recovery by best cosine match per true feature.

    Returns:
        ``(mean_best_cosine, fraction_at_0_90)``.
    """

    similarities = normalize_rows(learned_atoms) @ normalize_rows(true_atoms).T
    best_per_truth = similarities.max(axis=0)
    return float(best_per_truth.mean()), float(np.mean(best_per_truth >= 0.90))


def orbit_closure_score(learned_atoms: FloatArray, config: OrbitSparseConfig) -> float:
    """Score whether learned atoms are closed under the cyclic group action.

    For each non-identity group action, each transformed atom should have a close
    neighbor elsewhere in the learned dictionary if the dictionary respects the
    orbit structure. The score is label-free and uses only the known action.
    """

    atoms = normalize_rows(learned_atoms)
    scores: list[FloatArray] = []
    for step in range(1, config.orbit_size):
        transformed = np.roll(atoms, step * config.shift, axis=1)
        similarities = transformed @ atoms.T
        np.fill_diagonal(similarities, 0.0)
        scores.append(similarities.max(axis=1))
    return float(np.mean(scores))
